In [2]:
#Numpy is fast, convinenet and less memory occupied
import numpy as np
import time
import sys


In [3]:
#range in list
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [5]:
#range in np
l=np.arange(1000)
print(l.size*l.itemsize)

8000


In [8]:
SIZE=100000
a1=np.arange(SIZE)
a2=np.arange(SIZE)
#in list
start=time.time()
result=[(x+y) for x,y in zip(a1,a2)]
print("Python List Took: ",(time.time()-start)*1000)
#in numpy
start=time.time()
result=a1+a2
print("Python Numpy Took: ",(time.time()-start)*1000)


Python List Took:  55.726051330566406
Python Numpy Took:  13.289928436279297


In [10]:
a1*a2

array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001])

# *numpy basic operation *

In [11]:
a= np.array([1,2,3])
a[1]

2

In [33]:
a=np.array([[1,2],[3,4],[5,6]]) #2d
#a=np.array([[[1,2],[3,4],[5,6]]]) #3d

print("Dimension of a: ",a.ndim)
print(a[1])

print("ITEM SIZE: ",a.itemsize)
print("Data type: ",a.dtype)
print("Size: ", a.size) #num of elements
print("Size: ", a.shape) #(row, colum)

Dimension of a:  2
[3 4]
ITEM SIZE:  8
Data type:  int64
Size:  6
Size:  (3, 2)


In [34]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float32) #2d
#a=np.array([[1,2],[3,4],[5,6]],dtype=compex) #2d

print("Data type: ",a.dtype)


Data type:  float32


In [36]:
#intialize all number in 3x4 np array with 0 or 1 

#np.zeros((3,4))

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.arange(1,5) #creat np array of 1 to 4

array([1, 2, 3, 4])

In [39]:
np.arange(1,5,2)#(starting point, ending point, step size)

array([1, 3])

In [40]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [47]:
a=np.array([[1,2],[3,4],[5,4]])
a

array([[1, 2],
       [3, 4],
       [5, 4]])

In [48]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 4]])

In [50]:
 #make 1D array
a.ravel()

array([1, 2, 3, 4, 5, 4])

In [52]:
#a.min()
a.max()


5

In [54]:
#a.sum()
a.sum(axis=0) #colum wise sum
a.sum(axis=1) #row wise sum

array([3, 7, 9])

In [56]:
#np.sqrt(a)
np.std(a)

1.3437096247164249

In [60]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [61]:
b=np.array([[1,2],[4,6]])
b

array([[1, 2],
       [4, 6]])

In [62]:
a+b

array([[ 2,  4],
       [ 7, 10]])

In [63]:
a/b

array([[1.        , 1.        ],
       [0.75      , 0.66666667]])

In [64]:
a-b

array([[ 0,  0],
       [-1, -2]])

In [65]:
a*b

array([[ 1,  4],
       [12, 24]])

In [66]:
a.dot(b)

array([[ 9, 14],
       [19, 30]])

**
1-Indexing and slicing 
2-Iteration through array
3-Stacking together two arrays
4-Inexing with boolean arrays
**

In [68]:
#list slicing
n=[6,7,8]
n[0:2] #print index from 0 to 1
# n[-1] print index form last

8

In [69]:
#numpy slicing
a=np.array([6,7,8])
a[0:2]
a[-1]

8

In [70]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [71]:
a[1,2]

3

In [72]:
a[0:2,2] #go through from 0 to 1 array and find 2nd index

array([8, 3])

In [73]:
a[-1]

array([9, 3, 2])

In [74]:
 a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [75]:
a[-1,0:2]

array([9, 3])

In [77]:
a[:,1:3] #a[all rows, colum from 1 to 2 ]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [78]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [79]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [80]:
  for cell in a.flat:
        print(cell)

6
7
8
1
2
3
9
3
2


In [81]:
b1=np.arange(6).reshape(3,2)
b2=np.arange(6,12).reshape(3,2)

In [82]:
b1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [83]:
b2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [86]:
np.vstack((b1,b2)) #concating colum

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [87]:
np.hstack((b1,b2)) #concating row

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [88]:
b3=np.arange(30).reshape(2,15)

In [89]:
b3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [91]:
np.hsplit(b3,3) #split array horizotal array

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [92]:
np.vsplit(b3,2) #split array on vertical array

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [94]:
b4=np.arange(12).reshape(3,4)

In [95]:
b4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
b5=b4>4
b5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [100]:
b4[b5] #print only true index 

array([ 5,  6,  7,  8,  9, 10, 11])

In [104]:
b4[b5]=-1
b4 #any element which is greater than 4 becaomes -1

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

**Looping NumPy**

In [105]:
k=np.arange(12).reshape(3,4)
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
for row in k:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [108]:
for cell in k.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [109]:
for x in np.nditer(k,order='C'):
    print(x)#print row wise

0
1
2
3
4
5
6
7
8
9
10
11


In [110]:
for x in np.nditer(k,order='F'):
    print(x)#print colum wise

0
4
8
1
5
9
2
6
10
3
7
11


In [111]:
for x in np.nditer(k,order='F',flags=['external_loop']):
    print(x)#Print colum wise

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [112]:
for x in np.nditer(k,op_flags=['readwrite']):
    x[...]=x*x

In [114]:
k

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [124]:
#Itearate two arrays simentaniously either shape same or on edimension is 1 in reshape
k1=np.arange(3).reshape(3,1)
k1


array([[0],
       [1],
       [2]])

In [125]:
for x,y in np.nditer([k,k1]):
    print(x,y)

0 0
1 0
4 0
9 0
16 1
25 1
36 1
49 1
64 2
81 2
100 2
121 2
